version: '3.8'

services:
  kali:
    build: ./kali
    container_name: kali
    networks:
      lab_net:
        ipv4_address: 192.168.56.1
    tty: true
    stdin_open: true
    command: /bin/bash

  owasp:
    image: citizenstig/nowasp
    container_name: owasp
    networks:
      lab_net:
        ipv4_address: 192.168.56.3
    ports:
      - "80:80"
      - "3306:3306"

  dns:
    build: ./dns
    container_name: dns
    networks:
      lab_net:
        ipv4_address: 192.168.56.4
    ports:
      - "53:53/udp"    # Espone il DNS in modo da poter interrogare il server
      - "53:53/tcp"    # (Eventualmente anche TCP se necessario)

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
