services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali
    networks:
      lan1:
        ipv4_address: 192.168.56.80
    tty: true

  ubuntu-dns:
    build:
      context: .
      dockerfile: Dockerfile.dns
    container_name: ubuntu-dns
    networks:
      lan1:
        ipv4_address: 192.168.56.79

  owasp:
    build:
      context: .
      dockerfile: Dockerfile.owasp
    container_name: owasp
    networks:
      lan1:
        ipv4_address: 192.168.56.102

  webtop:
    image: lscr.io/linuxserver/webtop:fedora-kde
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=demo         # Cambia se vuoi
      - PASSWORD=demo     # Cambia se vuoi
    networks:
      lan1:
        ipv4_address: 192.168.56.101
    # Espone la porta 3000 (o altra) per l'interfaccia web
    ports:
      - 3000:3000
    shm_size: "2gb"
    restart: unless-stopped
    dns:
     - 192.168.56.79


networks:
  lan1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
          gateway: 192.168.56.1

